version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - "es-node-1:elasticsearch"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  es-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es-node-1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_node-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./logs:/var/logs/mount
      - ./data:/var/data/mount
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"